[platformio]
default_envs = esp32dev_st7735
build_cache_dir = .pio/build_cache

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder
monitor_echo = true
lib_deps = 
	https://github.com/KiraFlux/KiraFlux-Toolkit.git
	okalachev/MAVLink@^2.0.22

build_flags =
	-std=gnu++17

build_unflags =
	-std=gnu++11

[env:esp32dev_st7735]
extends = env:esp32dev
build_flags = ${env:esp32dev.build_flags} -DDJC_DISPLAY_DRIVER_ST7735 -DDJC_UI_RENDERER_IMPL_TEXTUAL_COLORED

[env:esp32dev_ssd1306]
extends = env:esp32dev
build_flags = ${env:esp32dev.build_flags} -DDJC_DISPLAY_DRIVER_SSD1306